-- Crear tabla de eventos del calendario
CREATE TABLE IF NOT EXISTS public.eventos_calendario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descripcion TEXT DEFAULT '',
  tipo TEXT NOT NULL CHECK (tipo IN ('actividad', 'deporte', 'gimnasio', 'home_office', 'trabajo_presencial', 'evento', 'compromiso', 'cita_medica')),
  persona TEXT NOT NULL CHECK (persona IN ('Melina', 'Tomas', 'Ambos')),
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE,
  hora_inicio TIME,
  hora_fin TIME,
  ubicacion TEXT DEFAULT '',
  notas TEXT DEFAULT '',
  color TEXT DEFAULT '#14b8a6',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_eventos_calendario_fecha_inicio
ON public.eventos_calendario (fecha_inicio);

CREATE INDEX IF NOT EXISTS idx_eventos_calendario_persona
ON public.eventos_calendario (persona);

CREATE INDEX IF NOT EXISTS idx_eventos_calendario_tipo
ON public.eventos_calendario (tipo);

-- Datos de ejemplo
INSERT INTO public.eventos_calendario (titulo, descripcion, tipo, persona, fecha_inicio, hora_inicio, hora_fin, ubicacion, color) VALUES
('Gimnasio - Rutina de piernas', 'Entrenamiento de piernas y glúteos', 'gimnasio', 'Melina', CURRENT_DATE + INTERVAL '1 day', '18:00', '19:30', 'Gimnasio SportClub', '#ef4444'),
('Reunión de equipo', 'Weekly team meeting', 'trabajo_presencial', 'Tomas', CURRENT_DATE + INTERVAL '2 days', '10:00', '11:00', 'Oficina - Sala de juntas', '#3b82f6'),
('Cita con el dentista', 'Control y limpieza dental', 'cita_medica', 'Melina', CURRENT_DATE + INTERVAL '3 days', '15:30', '16:30', 'Consultorio Dr. García', '#f59e0b'),
('Partido de fútbol', 'Partido con amigos del barrio', 'deporte', 'Tomas', CURRENT_DATE + INTERVAL '4 days', '20:00', '22:00', 'Cancha del club', '#10b981'),
('Home Office', 'Trabajo desde casa - proyecto nuevo', 'home_office', 'Melina', CURRENT_DATE + INTERVAL '5 days', '09:00', '17:00', 'Casa', '#8b5cf6'),
('Cena con los padres', 'Cena familiar en casa de los suegros', 'evento', 'Ambos', CURRENT_DATE + INTERVAL '6 days', '20:30', '23:00', 'Casa de los padres', '#ec4899');
