-- Crear tabla de tareas del hogar
CREATE TABLE IF NOT EXISTS public.tareas_hogar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descripcion TEXT DEFAULT '',
  categoria TEXT NOT NULL CHECK (categoria IN ('limpieza', 'compras', 'reparaciones', 'mantenimiento', 'cocina', 'otros')),
  prioridad TEXT NOT NULL CHECK (prioridad IN ('baja', 'media', 'alta', 'urgente')) DEFAULT 'media',
  asignado_a TEXT CHECK (asignado_a IN ('Melina', 'Tomas', 'Ambos')),
  completada BOOLEAN DEFAULT FALSE,
  fecha_limite DATE,
  fecha_completada DATE,
  notas TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Crear tabla de inventario del hogar
CREATE TABLE IF NOT EXISTS public.inventario_hogar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  categoria TEXT NOT NULL CHECK (categoria IN ('alimentos', 'bebidas', 'limpieza', 'higiene', 'medicamentos', 'otros')),
  cantidad INTEGER NOT NULL DEFAULT 0,
  unidad TEXT DEFAULT 'unidades',
  minimo_stock INTEGER DEFAULT 1,
  ubicacion TEXT DEFAULT '',
  fecha_vencimiento DATE,
  notas TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_tareas_hogar_completada ON public.tareas_hogar (completada);
CREATE INDEX IF NOT EXISTS idx_tareas_hogar_categoria ON public.tareas_hogar (categoria);
CREATE INDEX IF NOT EXISTS idx_inventario_hogar_categoria ON public.inventario_hogar (categoria);
CREATE INDEX IF NOT EXISTS idx_inventario_hogar_stock ON public.inventario_hogar (cantidad, minimo_stock);

-- Datos de ejemplo para tareas
INSERT INTO public.tareas_hogar (titulo, descripcion, categoria, prioridad, asignado_a, fecha_limite, notas) VALUES
('Comprar leche', 'Se acabó la leche, comprar 2 litros', 'compras', 'media', 'Ambos', CURRENT_DATE + INTERVAL '2 days', 'Preferir descremada'),
('Atornillar pizarra', 'La pizarra de la cocina se está cayendo', 'reparaciones', 'alta', 'Tomas', CURRENT_DATE + INTERVAL '1 day', 'Usar tornillos largos'),
('Limpiar heladera', 'Limpieza profunda y revisar vencimientos', 'limpieza', 'media', 'Melina', CURRENT_DATE + INTERVAL '3 days', 'Sacar todo antes de limpiar'),
('Comprar productos de limpieza', 'Falta detergente y lavandina', 'compras', 'baja', 'Ambos', CURRENT_DATE + INTERVAL '5 days', 'Aprovechar ofertas del super'),
('Cambiar filtro de agua', 'Ya pasaron 3 meses del último cambio', 'mantenimiento', 'media', 'Tomas', CURRENT_DATE + INTERVAL '7 days', 'Comprar filtro compatible');

-- Datos de ejemplo para inventario
INSERT INTO public.inventario_hogar (nombre, categoria, cantidad, unidad, minimo_stock, ubicacion, fecha_vencimiento, notas) VALUES
('Naranjas', 'alimentos', 8, 'unidades', 3, 'Heladera - cajón frutas', CURRENT_DATE + INTERVAL '7 days', 'Para jugo matutino'),
('Coca Cola', 'bebidas', 1, 'botella 2L', 1, 'Heladera - puerta', CURRENT_DATE + INTERVAL '30 days', 'Para ocasiones especiales'),
('Agua mineral', 'bebidas', 1, 'botella 2L', 2, 'Despensa', CURRENT_DATE + INTERVAL '365 days', 'Siempre tener de repuesto'),
('Detergente', 'limpieza', 0, 'botella', 1, 'Bajo mesada cocina', NULL, 'Se terminó - comprar urgente'),
('Leche', 'alimentos', 0, 'litro', 1, 'Heladera', NULL, 'Se terminó - comprar'),
('Papel higiénico', 'higiene', 4, 'rollos', 2, 'Baño - armario', NULL, 'Stock suficiente'),
('Aceite de cocina', 'alimentos', 1, 'botella', 1, 'Despensa', CURRENT_DATE + INTERVAL '180 days', 'Medio uso'),
('Shampoo', 'higiene', 2, 'botella', 1, 'Baño - ducha', NULL, 'Uno abierto, uno de repuesto');
